### PR TITLE
fix/build: change reqwest library to http_req

### PR DESCRIPTION
**Pull request by jacderida**
We found the reqwest library didn't seem to be working correctly, so we've replaced it with another http request library that can download the archive.

@povilasb sat and walked me through this.

### CODE REVIEW

**Comment by pierrechevalier83** [comment]
The change looks good to me although the git history of this PR seems a bit convoluted (I see 2 "fix typo" commits that seem to be the same one).
I would be for having a linear history of 2 commits:
* the one that updates rust with the typo fix squashed (sorry for the typo, btw)
* the one that replaces reqwest

**Comment by pierrechevalier83** [comment]
I'm now happy with the content of both commits but could you reword the second one?

"fix typo" is not what this commit does.
```
chore/ci: update scripts to rust stable 1.29.0

This allows to install rustfmt and clippy on stable with rustup.

Drop nightly as it was mostly needed for rustfmt and clippy.
```
would be a better commit message :)

**Comment by jacderida** [comment]
@pierrechevalier83 Sorry about that, got into a bit of a mess with the rebase. Sorted now thanks to @nbaksalyar :).

**Review by pierrechevalier83 — APPROVED** [review]
Looks good to me. Thanks for this work, @jacderida. It's gonna be useful for everyone :smile:

**Review by nbaksalyar — APPROVED** [review]

**Pull request merged**
