### PR TITLE
Fix lint warnings.

### PR DESCRIPTION
**Pull request by Fraser999**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/rust_sodium/13)

### CODE REVIEW

**Comment by dirvine** [comment]
Reviewed 14 of 48 files at r1.
Review status: 14 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/crypto/auth/auth_macros.rs, line 50 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPlfcYB_QwFDwuUWBOy:-KPlfcYCEzGNvVnT5NzM:buu6uin) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L50)):_

> ``` Rust
>     unsafe {
>         let mut tag = [0; TAGBYTES];
>         assert_eq!(0, $auth_name(tag.as_mut_ptr(),
> ```

Why assert here? not debug_assert or perhaps even a message? Requiring this may invalidate macro use of the verify mechanism and better force folk to use a function proper. Leads to larger point of defined error codes in this crate. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13)_

**Comment by Fraser999** [comment]
Review status: 14 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/crypto/auth/auth_macros.rs, line 50 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPlfcYB_QwFDwuUWBOy:-KPljckVKGncM2hMtj6b:bwvhefo) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L50)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> Why assert here? not debug_assert or perhaps even a message? Requiring this may invalidate macro use of the verify mechanism and better force folk to use a function proper. Leads to larger point of defined error codes in this crate. 
> </details>
> At the moment, any errors (i.e. non-zero return from the C-lib) are being ignored (the newly-introduced lint checks exposed many such cases).  Having looked at a couple of these functions in the C-lib, they can't possibly return anything except `0`.  I haven't checked many since it'd be a long process.  The actual C code being run is defined in multiple places depending on target arch and other PP defs.  I imagine at least _some_ of them will have other possible return values apart from `0`.

The proper way to handle this is probably to change the return type of the Rust wrappers to something like a `Result<(), i64>` (or as you mentioned, something more meaningful than `()` or `i64`), but only for those wrappers where it makes sense - i.e. those which are capable of returning non-zero values.  For wrappers which can't fail, the `assert` future-proofs us somewhat against the C lib changing to return non-zero values in subsequent versions.

I don't think this should be a `debug_assert` since that won't get picked up by CI tests, and probably won't get picked up by devs either as most are running tests in Release mode AFAIK.

If we decide to go with returning a `Result`, this will take quite a while to implement (spent finding out which wrappers actually need it and which should be left as asserts) and will also probably require quite a lot of work in dependent crates (e.g. deciding how to handle failure to generate a key-pair).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13)_

**Comment by dirvine** [comment]
Review status: 14 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/crypto/auth/auth_macros.rs, line 50 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPlfcYB_QwFDwuUWBOy:-KPsggqm-BQM9LoPlHYT:biriqru) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L50)):_
<details><summary>

<i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>



> At the moment, any errors (i.e. non-zero return from the C-lib) are being ignored (the newly-introduced lint checks exposed many such cases).  Having looked at a couple of these functions in the C-lib, they can't possibly return anything except `0`.  I haven't checked many since it'd be a long process.  The actual C code being run is defined in multiple places depending on target arch and other PP defs.  I imagine at least _some_ of them will have other possible return values apart from `0`.
> 
> The proper way to handle this is probably to change the return type of the Rust wrappers to something like a `Result<(), i64>` (or as you mentioned, something more meaningful than `()` or `i64`), but only for those wrappers where it makes sense - i.e. those which are capable of returning non-zero values.  For wrappers which can't fail, the `assert` future-proofs us somewhat against the C lib changing to return non-zero values in subsequent versions.
> 
> I don't think this should be a `debug_assert` since that won't get picked up by CI tests, and probably won't get picked up by devs either as most are running tests in Release mode AFAIK.
> 
> If we decide to go with returning a `Result`, this will take quite a while to implement (spent finding out which wrappers actually need it and which should be left as asserts) and will also probably require quite a lot of work in dependent crates (e.g. deciding how to handle failure to generate a key-pair).
> </details>
> My worry here is that we crash applications though. Perhaps lets come up with some options on how to handle this, assert being the sledgehammer and ignore being the opposite. It may be we have a function to check non zero and return some error that we check further up, not sure. 

Is there a way to not assert in this at the moment and take that as a separate PR? sry for the hassle but I think assert may prove problematic, almost as much as ignoring errors granted. So not saying ignore this, but perhaps it does need fixed proper? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13)_

**Comment by dirvine** [comment]
Review status: 14 of 48 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/crypto/auth/auth_macros.rs, line 77 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPshQqq9zE4FsOEGLYj:-KPshQqrQtL6tpPqe83i:b-ea92tz) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L77)):_

> ``` Rust
>     fn test_auth_verify() {
>         use randombytes::randombytes;
>         assert!(::init());
> ```

If we did handle errors, perhaps this is all a result ? 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13)_

**Comment by Fraser999** [comment]
Review status: 14 of 48 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/crypto/auth/auth_macros.rs, line 50 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPlfcYB_QwFDwuUWBOy:-KPvXdD37p8SA3iId2X-:bhfnkw5) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L50)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> My worry here is that we crash applications though. Perhaps lets come up with some options on how to handle this, assert being the sledgehammer and ignore being the opposite. It may be we have a function to check non zero and return some error that we check further up, not sure. 
> 
> Is there a way to not assert in this at the moment and take that as a separate PR? sry for the hassle but I think assert may prove problematic, almost as much as ignoring errors granted. So not saying ignore this, but perhaps it does need fixed proper? 
> </details>
> I think we're roughly in agreement about the proper fix being that these functions should return `Result`s, and that that should be a separate PR altogether.  If that's the case, then for these functions, we _have_ to either ignore the error or panic.  I'm very much in favour of the latter, but if you want the former, I'll revert these `assert`s and ignore the result using a variable like `_todo_use_result` for each instance so we can find them again easily.

---

_[src/crypto/auth/auth_macros.rs, line 77 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPshQqq9zE4FsOEGLYj:-KPv_ETYpGfebD92p3Dm:b-ayjywi) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L77)):_
<details><summary>

<i>Previously, dirvine (David Irvine) wrote…</i></summary>



> If we did handle errors, perhaps this is all a result ? 
> </details>
> Yeah, `init()` could return `Result<(), Error>` instead of `bool` and then we just do `unwrap!(::init());` instead once we change to use errors throughout.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13)_

**Comment by dirvine** [comment]
:lgtm:

---

Reviewed 26 of 48 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/crypto/auth/auth_macros.rs, line 50 [r1]](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-KPlfcYB_QwFDwuUWBOy:-KPvhmyO1NLZuWwULd_k:b9x8joz) ([raw file](https://github.com/maidsafe/rust_sodium/blob/b83da5c89eb73c37346d5803aa1f1ea277dc44f5/src/crypto/auth/auth_macros.rs#L50)):_
<details><summary>

<i>Previously, Fraser999 (Fraser Hutchison) wrote…</i></summary>



> I think we're roughly in agreement about the proper fix being that these functions should return `Result`s, and that that should be a separate PR altogether.  If that's the case, then for these functions, we _have_ to either ignore the error or panic.  I'm very much in favour of the latter, but if you want the former, I'll revert these `assert`s and ignore the result using a variable like `_todo_use_result` for each instance so we can find them again easily.
> </details>
> Ah cool, I think pre beta this is a must now to introduce an error class and use this throughout. With that refactr also introduce the easy_box functions as well. So lets scope that out and we can look at that as a priority task, before we declare secure working here. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/rust_sodium/13#-:-KPvibfoDwlp4S7Mcaxl:bnfp4nl)_

**Pull request merged**
